### ISSUE TITLE
Issue in /src/pages/guides/plugins/index.md

### ISSUE THREAD

**Issue by psphilippe** [AdobeDocs/adobe-dev-console#105] opened 2023-07-12 03:54 UTC
#### Logs taken while reproducing problem

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/AdobeDocs/adobe-dev-console/issues/124
- [ ] https://github.com/AdobeDocs/adobe-dev-console/issues/125
```

**Comment by theManikJindal** [comment] 2024-05-27 11:46
Closing this issue as the issue is not described.

**Closed by theManikJindal** 2024-05-27 11:46 UTC
